openapi: 3.1.0
info:
  title: CG Notion API
  description: API for managing architects, words, and daily entries in the Notion system.
  version: 1.0.0
servers:
  - url: https://cg-notion.vercel.app
    description: Production server
paths:
  /api/summarize:
    get:
      operationId: summarizeUrl
      summary: Generate a summarization prompt for a URL.
      description: This endpoint accepts a URL as a query parameter and returns a prompt for summarizing the content at the URL.
      parameters:
        - name: url
          in: query
          description: The URL of the content to summarize.
          required: true
          schema:
            type: string
            format: uri
      responses:
        '200':
          description: A successful response containing the summarization prompt.
          content:
            application/json:
              schema:
                type: object

                properties:
                  transcript:
                    type: string
                    description: YouTube's automatic transcript of the video.
                  prompt:
                    type: string
                    description: The generated summarization prompt.
        '400':
          description: Bad request due to invalid or missing URL.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating the issue.
  /api/daily:
    post:
      operationId: createDailyEntry
      summary: Creates a daily entry in the Notion system.
      description: >
        This endpoint allows users to create a daily entry in the Notion system 
        by providing a `name` field in the request body. 
        Requires an `X-NOTION-TOKEN` header for authentication and an `Origin` header.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DailyEntryRequest'
      responses:
        '200':
          description: Entry created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DailyEntryResponse'
        '400':
          description: Bad Request - Invalid input data.
        '401':
          description: Unauthorized - Missing or invalid `X-NOTION-TOKEN`.
      security:
        - notionAuth: [ ]
  /api/architects:
    post:
      operationId: createArchitect
      summary: Creates a new architect entry in the Notion system.
      description: >
        This endpoint allows users to create a new architect entry by providing
        required fields such as `emoji`, `name`, `overview`, `works`, `philosophy`, and `externalLinks`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArchitectRequest'
      responses:
        '200':
          description: Architect entry created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: The URL of the created architect entry in Notion.
        '400':
          description: Bad Request - Invalid input data.
        '500':
          description: Internal Server Error - Failed to create a page in Notion.
  /api/words:
    post:
      operationId: createWord
      summary: Creates a new word entry in the Notion system.
      description: >
        This endpoint allows users to create a new word entry by providing
        fields such as `emoji`, `name`, `pronunciation`, `definition`, `example`, and `type`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WordRequest'
      responses:
        '200':
          description: Word entry created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: The URL of the created word entry in Notion.
        '400':
          description: Bad Request - Invalid input data.
        '500':
          description: Internal Server Error - Failed to create a page in Notion.
components:
  securitySchemes:
    notionAuth:
      type: apiKey
      in: header
      name: X-NOTION-TOKEN
  schemas:
    DailyEntryRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the daily entry.
      required:
        - name
    DailyEntryResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the entry was created successfully.
        url:
          type: string
          description: The URL of the created entry.
    ArchitectRequest:
      type: object
      properties:
        emoji:
          type: string
          description: 建築家のイメージに合う絵文字
        name:
          type: object
          description: 建築家の名前
          properties:
            jp:
              type: string
              description: 日本語表記名
            en:
              type: string
              description: 英語表記名
          required:
            - jp
            - en
        overview:
          type: object
          description: 建築家の概要
          properties:
            imageUrls:
              type: array
              items:
                type: string
                description: 建築家や建築の画像URL
            description:
              type: array
              items:
                type: string
                description: 500文字程度の概要
          required:
            - imageUrls
            - description
        works:
          type: array
          description: 建築家の代表作のリスト
          items:
            type: object
            properties:
              title:
                type: string
                description: 建築名
              createdAt:
                type: number
                format: int64
                description: 施工年月
              location:
                type: string
                description: 所在地
              description:
                type: string
                description: 建築物の説明
              url:
                type: string
                description: 建築物画像のURL
            required:
              - title
              - createdAt
              - location
              - description
              - url
        philosophy:
          type: array
          description: 建築哲学や特徴
          items:
            type: string
        externalLinks:
          type: array
          description: 外部リンクのリスト
          items:
            type: object
            properties:
              title:
                type: string
                description: リンク名
              url:
                type: string
                description: リンクURL
            required:
              - title
              - url
      required:
        - emoji
        - name
        - overview
        - works
        - philosophy
        - externalLinks
    WordRequest:
      type: object
      properties:
        emoji:
          type: string
          description: 文字のイメージに合う絵文字
        name:
          type: string
          description: 日本語表記名
        pronunciation:
          type: string
          description: 読み方
        def:
          type: string
          description: 定義
        example:
          type: string
          description: 例文
        type:
          type: string
          enum:
            - 建築
            - 慣用句
            - ビジネス
            - 技術
            - 哲学
            - その他
            - 食べ物
            - 科学
            - 心理学
            - 仮想通貨
            - 金融工学
            - 芸術
            - 旅
          description: カテゴリー
      required:
        - emoji
        - name
        - pronunciation
        - def
        - example
        - type
